# Describes the format for available scene services

turn_on:
  description: Activate a scene.
  fields:
    entity_id:
      description: Name(s) of scenes to turn on
      example: "scene.romantic"

reload:
  description: Reload the scene configuration

apply:
  description: Activate a scene. Takes same data as the entities field from a single scene in the config.
  fields:
    entities:
      description: The entities and the state that they need to be.
      example:
        light.kitchen: "on"
        light.ceiling:
          state: "on"
          brightness: 80
