browse_url:
  description: Open a URL in the default browser on the host machine of Home Assistant.
  fields:
    url:
      description: The URL to open.
      example: "https://www.home-assistant.io"
